steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/g-one-db/prehospital-ml-api:v1.0.0', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/g-one-db/prehospital-ml-api:v1.0.0']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'mlapi', '--image', 'gcr.io/g-one-db/prehospital-ml-api:v1.0.0', '--region', 'asia-southeast2', '--platform', 'managed']
images:
- gcr.io/g-one-db/prehospital-ml-api:v1.0.0